// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {apiclient} from '../models';

export function GetStatus():Promise<main.Status>;

export function ListShows():Promise<Array<apiclient.Show>>;
